export const API_URL = "https://api.unsplash.com";
export const API_URL_PHOTOS = `${API_URL}/photos`;
export const API_URL_TOKEN = "https://unsplash.com/oauth/token";
export const ACCESS_KEY = "GVlNFCrpedUyMJ8Ab1WoPyY_lr09thcoXPmBQwlmcDc";
export const SECRET_KEY = "FQxiiJTmEe1EuAX3PisciNPfXfc0-YIdNEy62mT6Jq0";
export const API_URL_AUTH = "https://unsplash.com/oauth/authorize";
export const REDIRECT_URI = "http://127.0.0.1:5500/index.html";
export const RESPONSE_TYPE = "code";
export const SCOPE = "public read_user read_photos write_likes";
